\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
here()
# Load your packages
library(tidyverse)
library(dplyr)
library(lubridate)
library(here)
library(trend)
library(tseries)
library(forecast)
# Set your ggplot theme
mytheme <- theme_bw()+
  theme(plot.title = element_text(hjust=0.5),
  plot.subtitle =element_text(hjust=0.5),
  text=element_text(size=12, family='sans'),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank())
# Load your datasets
# Import data set and drop first 4 rows
Michigan_raw<- read.csv(file=here("Data/Michigan_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Minnesota_raw<- read.csv(file=here("Data/Minnesota_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Nevada_raw<- read.csv(file=here("Data/Nevada_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
New_Mexico_raw<- read.csv(file=here("Data/New_Mexico_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
California_raw<- read.csv(file=here("Data/California_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Connecticut_raw<- read.csv(file=here("Data/Connecticut_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Illinois_raw<- read.csv(file=here("Data/Illinois_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Maine_raw<- read.csv(file=here("Data/Maine_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
New_York_raw<- read.csv(file=here("Data/New_York_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Oregon_raw<- read.csv(file=here("Data/Oregon_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Virginia_raw<- read.csv(file=here("Data/Virginia_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
Washington_raw<- read.csv(file=here("Data/Washington_Net_generation_for_all_sectors.csv"),
           stringsAsFactors = TRUE, skip=4)
# Remove the first 4 rows with no useful information
# Transpose the dataframe
# Convert to a data frame and set column names
# Drop the first 3 rows and repeated columns
# Generate sequence of dates starting from January 2001
# Add a 'State' column indicating 'Michigan'
# Rename columns for clarity
Michigan <- Michigan_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Michigan")

Minnesota <- Minnesota_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Minnesota")

Nevada <- Nevada_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Nevada")

New_Mexico <- New_Mexico_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "New_Mexico")

California <- California_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "California")

Connecticut <- Connecticut_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Connecticut")

Illinois <- Illinois_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Illinois")

Maine <- Maine_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Maine")

New_York <- New_York_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "New_York")

Oregon <- Oregon_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Oregon")

Virginia <- Virginia_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Virginia")

Washington <- Washington_raw %>%
  slice(-c(1:4)) %>%
  t() %>%
  as.data.frame(stringsAsFactors = FALSE) %>%
  setNames(.[1, ]) %>%
  .[-c(1:3), ] %>%
  select(-c(11:13)) %>%
  mutate(Date = seq(as.Date("2001-01-01"), by = "1 month", length.out = nrow(.)),
         State = "Washington")
#build a function to change the name of columns
set_column_names <- function(data) {
  names(data) <- c(
    "All fuels",
    "coal",
    "petroleum liquids",
    "petroleum coke",
    "natural gas",
    "other gases",
    "nuclear",
    "conventional hydroelectric",
    "other renewables",
    "other renewables:wind",
    "other renewables:geothermal",
    "other renewables:biomass",
    "biomass:wood and wood-derived fuels",
    "biomass:other biomass",
    "hydro-electric pumped storage",
    "other",
    "all solar",
    "small-scale solar photovoltaic",
    "all utility-scale solar",
    "all utility-scale solar:utility-scale photovoltaic",
    "all utility-scale solar:utility-scale thermal",
    "Date",
    "State"
  )
  rownames(data) <- seq_len(nrow(data))
  return(data)
}
#Rename columns
Michigan <- set_column_names(Michigan)
Minnesota <- set_column_names(Minnesota)
Nevada <- set_column_names(Nevada)
New_Mexico <- set_column_names(New_Mexico)
California <- set_column_names(California)
Connecticut <- set_column_names(Connecticut)
Illinois <- set_column_names(Illinois)
Maine <- set_column_names(Maine)
New_York <- set_column_names(New_York)
Oregon <- set_column_names(Oregon)
Virginia <- set_column_names(Virginia)
Washington <- set_column_names(Washington)
#Build a function to convert columns to numeric
convert_columns_to_numeric <- function(data) {
  columns_to_convert <- 1:(ncol(data) - 2)
  data[, columns_to_convert] <- apply(data[, columns_to_convert], 2, as.numeric)
  return(data)
}
#Convert to numeric
Michigan <- convert_columns_to_numeric(Michigan)
Minnesota <- convert_columns_to_numeric(Minnesota)
Nevada <- convert_columns_to_numeric(Nevada)
New_Mexico <- convert_columns_to_numeric(New_Mexico)
California <- convert_columns_to_numeric(California)
Connecticut <- convert_columns_to_numeric(Connecticut)
Illinois <- convert_columns_to_numeric(Illinois)
Maine <- convert_columns_to_numeric(Maine)
New_York <- convert_columns_to_numeric(New_York)
Oregon <- convert_columns_to_numeric(Oregon)
Virginia <- convert_columns_to_numeric(Virginia)
Washington <- convert_columns_to_numeric(Washington)
#Generate a dataframe with all states
combined_df <- rbind(Michigan, Minnesota, Nevada, New_Mexico, California, Connecticut,  Illinois, Maine,New_York, Oregon, Virginia, Washington)
```

# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 
```{r}
california <- read.csv(here('Processed/California.csv'))
california <- california %>% 
  mutate(Date = ymd(Date)) %>% 
  replace(is.na(.),0) %>%
  select(All.fuels, Date)
caliallfuelts <- ts(california$All.fuels, start = c(2001,1),frequency = 12)
```

```{r}
decompose <- decompose(caliallfuelts)
plot(decompose)
adf.test(caliallfuelts, alternative="stationary", k=0)
```


\newpage

# Analysis
```{r}
csvs <- list.files(path = here('Processed'),pattern = "\\.csv$", full.names = TRUE)

file_name <- c('California','combined_df', 'Connecticut', 
               'Illinois', 'Maine', 'Michigan', 'Minnesota', 
               'Nevada', 'New_Mexico', 'New_York', 
               'Oregon', 'Virginia', 'Washington')

names(csvs) <- file_name


# set a theme for plots
mytheme <- theme_bw()+
  theme(plot.title = element_text(hjust=0.5),
  plot.subtitle =element_text(hjust=0.5),
  text=element_text(size=12, family='sans'),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank())
```

```{r}
csv_reader <- function(state_name) {
  file_i <- read.csv(csvs[[state_name]], stringsAsFactors = TRUE)
}

data_wrangler <- function(state_name){
  state_data <- csv_reader(state_name) %>% 
    mutate(Date = ymd(Date)) %>% 
    replace(is.na(.),0) %>%
    select(All.fuels, Date)
  }
```

```{r}
plotting_function <- function(state_name){ggplot(data_wrangler(state_name), 
                                            aes(x=Date, y=All.fuels))+
    geom_line(color='darkslategray3')+
    geom_smooth(method = 'loess', color='coral')+
    scale_x_date(breaks=scales::breaks_pretty(10))+
    scale_y_continuous(breaks=scales::breaks_pretty(10))+
    labs(y= 'All Fuels', x='Date', title='All Fuels', subtitle = paste(state_name,'(2001.1-2023.8)'))+
    mytheme
  }
```

```{r}
# Create a function that plots arima ts forecast 
arima_ts <- function(state_name,t){
  state_data <- data_wrangler(state_name)
  f_month = month(first(state_data$Date))
  f_year = year(first(state_data$Date))
  all.fuel.ts <- ts(
    state_data$All.fuels,
    start = c(f_year, f_month),
    frequency = 12)
  all.fuel.arima <- auto.arima(all.fuel.ts)
  all.fuel.forecast <- forecast(all.fuel.arima, level=c(95), h=t*12)
  plot <- autoplot(all.fuel.forecast)+
    labs(y= 'All Fuel', x='Date', title='All Fuel Forecast', subtitle = paste(state_name,'(2001.1-2023.8)'))+
    mytheme
  last.forecast <- all.fuel.forecast$mean[length(all.fuel.forecast$mean)]
  print(plot)
  return(last.forecast)
}
```

```{r}
plotting_function('California')
arima_ts('California', 23)
```
```{r}
plotting_function('Connecticut')
arima_ts('Connecticut', 17)
```
```{r}
plotting_function('Illinois')
arima_ts('Illinois', 27)
```
```{r}
plotting_function('Maine')
arima_ts('Maine', 27)
```
```{r}
plotting_function('Michigan')
arima_ts('Michigan', 17)
```
```{r}
plotting_function('Minnesota')
arima_ts('Minnesota', 17)
```
```{r}
plotting_function('Nevada')
arima_ts('Nevada', 27)
```
```{r}
plotting_function('New_Mexico')
arima_ts('New_Mexico', 22)
```
```{r}
plotting_function('New_York')
arima_ts('New_York', 17)
```
```{r}
plotting_function('Oregon')
arima_ts('Oregon', 17)
```
```{r}
plotting_function('Virginia')
arima_ts('Virginia', 27)
```
```{r}
plotting_function('Washington')
arima_ts('Washington', 22)
```


## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
