---
title: "PercentageGrowth"
author: "Lucy Wang"
date: "2023-12-06"
output: pdf_document
---
# Research Question: how will the percentage of clean energy generation grow for each of the 12 states? 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
# load packages
library(here)
library(tidyverse)
library(lubridate)
library(trend)
library(tseries)
library(forecast)

# select files 
file_list <-
  list.files(
    path = here('Processed'),pattern = "\\.csv$", full.names = TRUE
  )
file_name <- c('California','combined_df', 'Connecticut', 
               'Illinois', 'Maine', 'Michigan', 'Minnesota', 
               'Nevada', 'New_Mexico', 'New_York', 
               'Oregon', 'Virginia', 'Washington')

names(file_list) <- file_name

#create a function that read csv files 
csv_reader <- function(state_name) {
  file_i <- read.csv(file_list[[state_name]], stringsAsFactors = TRUE)
}

# set a theme for plots
mytheme <- theme_bw()+
  theme(plot.title = element_text(hjust=0.5),
  plot.subtitle =element_text(hjust=0.5),
  text=element_text(size=12, family='sans'),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank())
```


```{r run sample, echo=FALSE}
# create a function that wrangles data, add a column for total clean energy generations and column for clean energy percentage 
data_wrangler <- function(state_name){
  state_data <- csv_reader(state_name) %>% 
    mutate(Date = ymd(Date)) %>% 
    replace(is.na(.),0) %>% 
    mutate(clean_energy = nuclear+
          conventional.hydroelectric+
          other.renewables+
          hydro.electric.pumped.storage+
          other) 
  }

```


```{r plotting, echo=FALSE}
# Create a function that plots past clean energy generation percentages  
plotting_function <- function(state_name){ggplot(data_wrangler(state_name), 
                                            aes(x=Date, y=clean_energy))+
    geom_line(color='darkslategray3')+
    geom_smooth(method = 'loess', color='coral')+
    scale_x_date(breaks=scales::breaks_pretty(10))+
    scale_y_continuous(breaks=scales::breaks_pretty(10))+
    labs(y= 'Clean Energy Generation (MWh)', x='Date', title='Clean Energy Generation (MWh)', subtitle = paste(state_name,'(2001.1-2023.8)'))+
    mytheme
  }
```

```{r ts, echo=FALSE}
# Create a function that plots arima ts forecast 
arima_ts <- function(state_name,t){
  state_data <- data_wrangler(state_name)
  f_month = month(first(state_data$Date))
  f_year = year(first(state_data$Date))
  clean.ts <- ts(
    state_data$clean_energy,
    start = c(f_year, f_month),
    frequency = 12)
  clean.arima <- auto.arima(clean.ts)
  clean.forecast <- forecast(clean.arima, level=c(95), h=t*12)
  plot <- autoplot(clean.forecast)+
    labs(y= 'Clean Energy Generation (MWh)', x='Date', title='Clean Energy Generation Forecast (MWh)', subtitle = paste(state_name,'(2001.1-2023.8)'))+
    mytheme
  last.forecast <- clean.forecast$mean[length(clean.forecast$mean)]
  print(plot)
  return(last.forecast)
}
```
### California 
```{r run functions California, echo=FALSE}
plotting_function('California')
arima_ts('California',23)
```
### Connecticut
```{r run functions Connecticut, echo=FALSE}
plotting_function('Connecticut')
arima_ts('Connecticut',17)
```
### Illinois
```{r run functions Illinois, echo=FALSE}
plotting_function('Illinois')
arima_ts('Illinois',27)
```
### Maine
```{r run functions Maine, echo=FALSE}
plotting_function('Maine')
arima_ts('Maine',27)
```
### Michigan 
```{r run functions Michigan, echo=FALSE}
plotting_function('Michigan')
arima_ts('Michigan',17)
```
### Minnesota
```{r run functions Minnesota, echo=FALSE}
plotting_function('Minnesota')
arima_ts('Minnesota',17)
```
### Nevada
```{r run functions Nevada, echo=FALSE}
plotting_function('Nevada')
arima_ts('Nevada',27)
```
### New Mexico
```{r run functions New Mexico, echo=FALSE}
plotting_function('New_Mexico')
arima_ts('New_Mexico',22)
```
### New York 
```{r run functions New York, echo=FALSE}
plotting_function('New_York')
arima_ts('New_York',17)
```
### Oregon
```{r run functions Oregon, echo=FALSE}
plotting_function('Oregon')
arima_ts('Oregon',17)
```
### Virginia
```{r run functions Virginia, echo=FALSE}
plotting_function('Virginia')
arima_ts('Virginia',27)
```
### Washington
```{r run functions Washington, echo=FALSE}
plotting_function('Washington')
arima_ts('Washington',22)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
